# Generated by Django 3.0.3 on 2020-03-31 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_price_area', models.CharField(choices=[('odds', '1万以内零星采购'), ('inquiry', '1-10万询价采购'), ('internal', '10-30万内部招标'), ('public', '30万以上公开招标')], max_length=64, verbose_name='采购方式')),
                ('project_type', models.CharField(choices=[('consumables', '耗材'), ('service', '维修'), ('maintain', '维保'), ('protocol', '政府协议供货'), ('blu_rayDisc', '蓝光盘'), ('tape', '数据流磁带'), ('operations', '技术运营')], max_length=64, verbose_name='采购类型')),
                ('name', models.CharField(max_length=128, verbose_name='项目名称')),
                ('manufacturer', models.CharField(max_length=128, verbose_name='供应商名称')),
                ('budget', models.FloatField(verbose_name='项目预算')),
                ('price', models.FloatField(verbose_name='项目总价')),
                ('charge_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='change_user', to=settings.AUTH_USER_MODEL, verbose_name='责任人')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_app.Department', verbose_name='所属部门')),
                ('pj_operator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pj_operator', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
                ('pj_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pj_user', to=settings.AUTH_USER_MODEL, verbose_name='使用人')),
            ],
            options={
                'verbose_name': '项目总表',
                'verbose_name_plural': '项目总表',
            },
        ),
    ]
