# Generated by Django 3.0.3 on 2020-04-01 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20200401_1455'),
        ('pj_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pj_plat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='user_app.Plat', verbose_name='所属平台'),
        ),
    ]
