# Generated by Django 3.0.3 on 2020-04-01 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pj_manage', '0001_initial'),
        ('user_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='耗材名称')),
                ('datetime', models.DateField(verbose_name='购买日期')),
                ('price', models.IntegerField(verbose_name='单价')),
                ('count', models.IntegerField(verbose_name='购买数量')),
                ('has_Warranty', models.BooleanField(verbose_name='是否保修')),
                ('warranty_time', models.DateField(verbose_name='保修日期')),
                ('has_contract', models.BooleanField(verbose_name='是否签署合同')),
                ('has_tender', models.BooleanField(verbose_name='是否招标')),
                ('charge_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='charge_user', to=settings.AUTH_USER_MODEL, verbose_name='责任人')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='operator', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pj_manage.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('it_device', 'it设备'), ('video', '视频设备'), ('audio', '音频设备'), ('other', '其他设备')], max_length=64, verbose_name='资产类型')),
                ('status', models.SmallIntegerField(choices=[(0, '在线'), (1, '下线'), (2, '未知'), (3, '故障'), (4, '备用'), (5, '待报废'), (6, '报废')], default=0, verbose_name='资产状态')),
                ('name', models.CharField(max_length=128, verbose_name='资产名称')),
                ('sn', models.CharField(max_length=128, verbose_name='资产序列号')),
                ('asset_id', models.IntegerField(verbose_name='资产编号')),
                ('price', models.FloatField(null=True, verbose_name='价格')),
                ('purchase_day', models.DateField(verbose_name='购买日期')),
                ('expire_day', models.DateField(verbose_name='过保日期')),
                ('memo', models.TextField(verbose_name='备注')),
                ('asset_charge_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset_charge_user', to=settings.AUTH_USER_MODEL, verbose_name='责任人')),
                ('asset_operator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset_operator', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
                ('asset_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset_user', to=settings.AUTH_USER_MODEL, verbose_name='使用人')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.Department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '资产总表',
                'verbose_name_plural': '资产总表',
                'ordering': ['asset_id'],
            },
        ),
    ]
