# Generated by Django 3.0.3 on 2020-03-31 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp_id', models.SmallIntegerField(null=True, verbose_name='部门编号')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='部门名称')),
            ],
            options={
                'verbose_name': '部门总表',
                'verbose_name_plural': '部门总表',
                'ordering': ['dp_id'],
            },
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_id', models.SmallIntegerField(null=True, verbose_name='平台编号')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='平台名称')),
            ],
            options={
                'verbose_name': '平台总表',
                'verbose_name_plural': '平台总表',
                'ordering': ['pt_id'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.SmallIntegerField(verbose_name='科室编号')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='科室名称')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.Department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '科室总表',
                'verbose_name_plural': '科室总表',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='plat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.Plat', verbose_name='所属平台'),
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=16, unique=True, verbose_name='员工编号')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='姓名')),
                ('phone', models.CharField(max_length=32, verbose_name='电话')),
                ('mobile_phone', models.CharField(max_length=32, verbose_name='手机')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.Department', verbose_name='所属部门')),
                ('plat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.Plat', verbose_name='所属平台')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.Section', verbose_name='所属科室')),
            ],
            options={
                'verbose_name': '员工总表',
                'verbose_name_plural': '员工总表',
            },
        ),
    ]
