# Generated by Django 3.0.3 on 2020-03-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EpManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_id',
            field=models.CharField(max_length=16, unique=True, verbose_name='员工编号'),
        ),
    ]
